
export const PData = [
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1B',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 2',
        subcategoria: 'Subcategoría 2A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
    {
        src: 'https://www.extintoresromagnoli.com/imgs/productos/productos35_2489.jpg',
        title: 'Titulo',
        category: 'Categoría 1',
        subcategoria: 'Subcategoría 1A',
    },
];
